import {
  AlarmClock,
  Ambulance,
  Anchor,
  ArrowBigUp,
  ArrowDownToLine,
  AudioLines,
  Backpack,
  Angry,
  Ban,
  Bandage,
  BatteryCharging,
  BatteryWarning,
  Beef,
  BellOff,
  BellRing,
  Biohazard,
  Bird,
  Bomb,
  Bone,
  Boxes,
  CheckCheck,
  ChevronsUp,
  CircleDot,
  CircleSlash,
  CircuitBoard,
  ClipboardList,
  Clock,
  CloudFog,
  Cog,
  Compass,
  Cpu,
  Crosshair,
  Crown,
  DoorClosed,
  DoorOpen,
  Drama,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  EarOff,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  Fingerprint,
  Fish,
  Flame,
  FlameKindling,
  FlipHorizontal,
  Footprints,
  Forward,
  Frame,
  Frown,
  Gauge,
  Gavel,
  Ghost,
  Grab,
  Hammer,
  Hand,
  HandHeart,
  Handshake,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Hourglass,
  Infinity as InfinityIcon,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  Lock,
  LockKeyhole,
  Megaphone,
  Moon,
  MoonStar,
  Music,
  Music2,
  Network,
  OctagonAlert,
  PackageX,
  Pause,
  PawPrint,
  PersonStanding,
  Pickaxe,
  Pill,
  Puzzle,
  Rabbit,
  Radar,
  Radiation,
  RadioTower,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  ScanEye,
  ScanFace,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Siren,
  Skull,
  Sparkle,
  Sparkles,
  Speech,
  Split,
  Star,
  Stethoscope,
  Sun,
  Swords,
  Syringe,
  Target,
  Telescope,
  Timer,
  TrendingUp,
  TriangleAlert,
  Unlock,
  User,
  UserCheck,
  UserX,
  Users,
  UsersRound,
  VenetianMask,
  Volume2,
  VolumeX,
  Warehouse,
  Waves,
  Waypoints,
  Wind,
  Wrench,
  Zap,
  ZapOff,
  type LucideIcon,
} from "lucide-react";
import type { PerkCategory, Role } from "@/types";

// ============================================================
// Original glyph language for perk emblems.
//
// We don't ship Behaviour Interactive's perk art. Instead every perk gets its
// own clean, role-tinted icon. PERK_GLYPH hand-picks a distinct, sensible glyph
// for each catalogued perk (a heart-pulse for Self-Care, a bomb for Pop Goes
// the Weasel, a beef cut for Barbecue & Chilli, an infinity for Hex: Undying…).
// CATEGORY_GLYPH is the safety net for anything not individually mapped.
// ============================================================

// One distinct glyph per perk, chosen to read like its effect.
const PERK_GLYPH: Record<string, LucideIcon> = {
  // ---- Survivor ----
  adrenaline: Zap,
  "decisive-strike": Unlock,
  "dead-hard": ShieldAlert,
  "off-the-record": VenetianMask,
  unbreakable: PersonStanding,
  "borrowed-time": Clock,
  "prove-thyself": Users,
  "deja-vu": Repeat,
  hyperfocus: Target,
  "stake-out": Crosshair,
  resilience: TrendingUp,
  "windows-of-opportunity": Frame,
  "sprint-burst": Rabbit,
  lithe: Wind,
  "balanced-landing": ArrowDownToLine,
  kindred: UsersRound,
  bond: Link,
  "iron-will": VolumeX,
  "urban-evasion": Footprints,
  "quick-and-quiet": BellOff,
  "dance-with-me": Music,
  "inner-strength": Sparkles,
  "built-to-last": RefreshCw,
  streetwise: Backpack,
  "circle-of-healing": HeartHandshake,
  "shadow-step": Moon,
  exponential: ArrowBigUp,
  "quick-gambit": Wrench,
  vigil: Timer,
  "self-care": HeartPulse,
  "botany-knowledge": Leaf,
  empathy: Heart,
  lightweight: Feather,
  // ---- Killer ----
  "pain-resonance": Anchor,
  "pop-goes-the-weasel": Bomb,
  deadlock: Lock,
  "corrupt-intervention": Ban,
  "grim-embrace": Hand,
  "dead-mans-switch": Pause,
  "lethal-pursuer": ScanEye,
  "nowhere-to-hide": Radar,
  "bbq-and-chili": Beef,
  "darkness-revealed": ScanSearch,
  "sloppy-butcher": Droplets,
  "hex-ruin": Flame,
  "hex-undying": InfinityIcon,
  "devour-hope": Skull,
  pentimento: FlameKindling,
  noed: Bone,
  "no-way-out": DoorClosed,
  bamboozle: FastForward,
  "coup-de-grace": Swords,
  tinkerer: Cog,
  "trail-of-torment": Ghost,
  "dark-devotion": RadioTower,
  "monitor-and-abuse": CircleDot,
  starstruck: Star,
  thanatophobia: HeartCrack,
  "spirit-fury": Hammer,
  enduring: Shield,
  lightborn: Sun,
  coulrophobia: HeartOff,
  eruption: Radiation,
  "infectious-fright": Volume2,
  "brutal-strength": Pickaxe,
  "a-nurses-calling": Eye,
  stridor: Ear,
  // ---- Teachables (completed roster) ----
  // survivor
  leader: Crown,
  "calm-spirit": Bird,
  saboteur: Scissors,
  "sole-survivor": User,
  "object-of-obsession": Telescope,
  "left-behind": Compass,
  technician: CircuitBoard,
  alert: BellRing,
  "boil-over": Waves,
  "detectives-hunch": Search,
  tenacity: Dumbbell,
  "red-herring": Fish,
  "for-the-people": HandHeart,
  "no-mither": Bandage,
  "were-gonna-live-forever": Ambulance,
  "better-together": Network,
  fixated: Route,
  visionary: Lightbulb,
  "desperate-measures": Stethoscope,
  clairvoyance: Sparkle,
  overcome: Forward,
  "corrective-action": CheckCheck,
  "wake-up": AlarmClock,
  pharmacy: Pill,
  "wide-open-throttle": Rocket,
  "lend-a-hand": Handshake,
  "cross-examination": Fingerprint,
  // killer
  "dragons-grip": Grab,
  "hex-blood-favour": Droplet,
  "hex-haunted-ground": TriangleAlert,
  rancor: Gavel,
  "beast-of-prey": PawPrint,
  "territorial-imperative": Warehouse,
  "hex-huntress-lullaby": Music2,
  "superior-anatomy": ChevronsUp,
  "awakened-awareness": ScanFace,
  terminus: Siren,
  "hex-two-can-play": FlipHorizontal,
  "friends-til-the-end": UserCheck,
  "batteries-included": BatteryCharging,
  "blood-echo": AudioLines,
  nemesis: UserX,
  "zanshin-tactics": Waypoints,
  "hex-nothing-but-misery": Frown,
  "forever-entwined": Link2,
  "none-are-free": LockKeyhole,
  "help-wanted": ClipboardList,
  "phantom-fear": Drama,
  haywire: ZapOff,
  "hex-plaything": Puzzle,
  "scourge-hook-gift-of-pain": Biohazard,
  hoarder: Boxes,
  oppression: Cpu,
  hysteria: EarOff,
  "hex-face-the-darkness": Megaphone,
  hubris: ShieldX,
  "franklins-demise": PackageX,
  "knock-out": MoonStar,
  dissolution: Split,
  "septic-touch": Syringe,
  "hex-the-third-seal": EyeOff,
  "hex-crowd-control": CircleSlash,
  "forced-penance": ShieldOff,
  deathbound: Speech,
  overcharge: BatteryWarning,
  "overwhelming-presence": Hourglass,
  "hex-scared-to-death": OctagonAlert,
  "silent-shadow": CloudFog,
  rampage: Angry,
};

const CATEGORY_GLYPH: Record<PerkCategory, LucideIcon> = {
  // survivor
  exhaustion: Wind,
  "aura-reading": Eye,
  "gen-repair": Wrench,
  healing: HeartPulse,
  stealth: EyeOff,
  boon: Sparkles,
  endgame: DoorOpen,
  "anti-tunnel": ShieldCheck,
  totem: Flame,
  utility: Settings,
  // killer
  "gen-slowdown": Gauge,
  hex: Skull,
  "anti-heal": Droplet,
  chase: Footprints,
  tracking: Radar,
  "scourge-hook": Anchor,
};

/** The emblem glyph for a perk: its hand-picked icon, else its primary category. */
export function glyphForPerk(
  slug: string,
  categories: readonly PerkCategory[] | undefined,
  role: Role,
): LucideIcon {
  return PERK_GLYPH[slug] ?? glyphForCategories(categories, role);
}

/** Pick the emblem glyph for a perk from its highest-signal category. */
export function glyphForCategories(
  categories: readonly PerkCategory[] | undefined,
  role: Role,
): LucideIcon {
  if (categories) {
    for (const c of categories) {
      const g = CATEGORY_GLYPH[c];
      if (g) return g;
    }
  }
  // No category match — fall back to a role-flavored default.
  return role === "killer" ? Ghost : ShieldCheck;
}
