import {
  AlarmClock,
  Ambulance,
  Anchor,
  ArrowBigUp,
  ArrowDownToLine,
  AudioLines,
  Backpack,
  Angry,
  Ban,
  Bandage,
  BatteryCharging,
  BatteryWarning,
  Beef,
  BellOff,
  BellRing,
  Biohazard,
  Bird,
  Bomb,
  Bone,
  Boxes,
  CheckCheck,
  ChevronsUp,
  CircleDot,
  CircleSlash,
  CircuitBoard,
  ClipboardList,
  Clock,
  CloudFog,
  Cog,
  Compass,
  Cpu,
  Crosshair,
  Crown,
  DoorClosed,
  DoorOpen,
  Drama,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  EarOff,
  Eye,
  EyeOff,
  FastForward,
  Feather,
  Fingerprint,
  Fish,
  Flame,
  FlameKindling,
  FlipHorizontal,
  Footprints,
  Forward,
  Frame,
  Frown,
  Gauge,
  Gavel,
  Ghost,
  Grab,
  Hammer,
  Hand,
  HandHeart,
  Handshake,
  Heart,
  HeartCrack,
  HeartHandshake,
  HeartOff,
  HeartPulse,
  Hourglass,
  Infinity as InfinityIcon,
  Leaf,
  Lightbulb,
  Link,
  Link2,
  Lock,
  LockKeyhole,
  Megaphone,
  Moon,
  MoonStar,
  Music,
  Music2,
  Network,
  OctagonAlert,
  PackageX,
  Pause,
  PawPrint,
  PersonStanding,
  Pickaxe,
  Pill,
  Puzzle,
  Rabbit,
  Radar,
  Radiation,
  RadioTower,
  RefreshCw,
  Repeat,
  Rocket,
  Route,
  ScanEye,
  ScanFace,
  ScanSearch,
  Scissors,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShieldOff,
  ShieldX,
  Siren,
  Skull,
  Sparkle,
  Sparkles,
  Speech,
  Split,
  Star,
  Stethoscope,
  Sun,
  Swords,
  Syringe,
  Target,
  Telescope,
  Timer,
  TrendingUp,
  TriangleAlert,
  Unlock,
  User,
  UserCheck,
  UserX,
  Users,
  UsersRound,
  VenetianMask,
  Volume2,
  VolumeX,
  Warehouse,
  Waves,
  Waypoints,
  Wind,
  Wrench,
  Zap,
  ZapOff,
  Activity,
  Airplay,
  Antenna,
  Aperture,
  Apple,
  Atom,
  Award,
  Axe,
  Banana,
  BatteryLow,
  Bean,
  Bed,
  BedDouble,
  Bell,
  BellDot,
  Binary,
  Binoculars,
  Blocks,
  Bolt,
  BookOpen,
  Bot,
  Box,
  Brain,
  BrainCircuit,
  BrickWall,
  Briefcase,
  Bug,
  Cake,
  Candy,
  Car,
  Castle,
  Cat,
  Cctv,
  Cherry,
  CircleDashed,
  Citrus,
  Clapperboard,
  Cloud,
  CloudRain,
  CloudSnow,
  Clover,
  Component,
  Cone,
  Construction,
  Contact,
  Cross,
  Dice5,
  Drill,
  FlaskConical,
  FlaskRound,
  Focus,
  Glasses,
  Grip,
  Hexagon,
  Layers,
  LifeBuoy,
  Locate,
  LocateFixed,
  LogOut,
  Magnet,
  MapPin,
  MapPinned,
  Medal,
  Navigation,
  Package,
  Pentagon,
  Radio,
  Rss,
  Sailboat,
  Satellite,
  SatelliteDish,
  ScanLine,
  Shapes,
  Shell,
  ShieldHalf,
  ShieldQuestion,
  Slice,
  Snail,
  Spade,
  Sunset,
  Tag,
  TimerOff,
  Turtle,
  Vault,
  View,
  Wand,
  Wand2,
  Webcam,
  ChevronsRight,
  Cookie,
  Cuboid,
  Dam,
  Database,
  Diamond,
  Disc,
  Disc3,
  Dog,
  Drum,
  Eclipse,
  Egg,
  Factory,
  Fan,
  Fence,
  FerrisWheel,
  Film,
  Filter,
  FireExtinguisher,
  Flag,
  Flower,
  Flower2,
  Forklift,
  Fuel,
  Gamepad2,
  Gem,
  GitBranch,
  Globe,
  GraduationCap,
  Grape,
  Grid2x2,
  HandCoins,
  HandHelping,
  HandMetal,
  HardHat,
  Headphones,
  Heater,
  Highlighter,
  Hop,
  IceCream,
  Image,
  Inbox,
  Joystick,
  Key,
  Lamp,
  LampDesk,
  Landmark,
  Lasso,
  Library,
  LightbulbOff,
  Lollipop,
  Luggage,
  Mailbox,
  Martini,
  Maximize,
  MemoryStick,
  Mic,
  MicOff,
  Microscope,
  Milestone,
  Mountain,
  MountainSnow,
  Mouse,
  Move,
  Notebook,
  PlugZap,
  Plus,
  Settings2,
  ShieldPlus,
  Sprout,
  type LucideIcon,
} from "lucide-react";
import type { PerkCategory, Role } from "@/types";

// ============================================================
// Original glyph language for perk emblems.
//
// We don't ship Behaviour Interactive's perk art. Instead every perk gets its
// own clean, role-tinted icon. PERK_GLYPH hand-picks a distinct, sensible glyph
// for each catalogued perk (a heart-pulse for Self-Care, a bomb for Pop Goes
// the Weasel, a beef cut for Barbecue & Chilli, an infinity for Hex: Undying…).
// CATEGORY_GLYPH is the safety net for anything not individually mapped.
// ============================================================

// One distinct glyph per perk, chosen to read like its effect.
const PERK_GLYPH: Record<string, LucideIcon> = {
  // ---- Survivor ----
  adrenaline: Zap,
  "decisive-strike": Unlock,
  "dead-hard": ShieldAlert,
  "off-the-record": VenetianMask,
  unbreakable: PersonStanding,
  "borrowed-time": Clock,
  "prove-thyself": Users,
  "deja-vu": Repeat,
  hyperfocus: Target,
  "stake-out": Crosshair,
  resilience: TrendingUp,
  "windows-of-opportunity": Frame,
  "sprint-burst": Rabbit,
  lithe: Wind,
  "balanced-landing": ArrowDownToLine,
  kindred: UsersRound,
  bond: Link,
  "iron-will": VolumeX,
  "urban-evasion": Footprints,
  "quick-and-quiet": BellOff,
  "dance-with-me": Music,
  "inner-strength": Sparkles,
  "built-to-last": RefreshCw,
  streetwise: Backpack,
  "circle-of-healing": HeartHandshake,
  "shadow-step": Moon,
  exponential: ArrowBigUp,
  "quick-gambit": Wrench,
  vigil: Timer,
  "self-care": HeartPulse,
  "botany-knowledge": Leaf,
  empathy: Heart,
  lightweight: Feather,
  // ---- Killer ----
  "pain-resonance": Anchor,
  "pop-goes-the-weasel": Bomb,
  deadlock: Lock,
  "corrupt-intervention": Ban,
  "grim-embrace": Hand,
  "dead-mans-switch": Pause,
  "lethal-pursuer": ScanEye,
  "nowhere-to-hide": Radar,
  "bbq-and-chili": Beef,
  "darkness-revealed": ScanSearch,
  "sloppy-butcher": Droplets,
  "hex-ruin": Flame,
  "hex-undying": InfinityIcon,
  "devour-hope": Skull,
  pentimento: FlameKindling,
  noed: Bone,
  "no-way-out": DoorClosed,
  bamboozle: FastForward,
  "coup-de-grace": Swords,
  tinkerer: Cog,
  "trail-of-torment": Ghost,
  "dark-devotion": RadioTower,
  "monitor-and-abuse": CircleDot,
  starstruck: Star,
  thanatophobia: HeartCrack,
  "spirit-fury": Hammer,
  enduring: Shield,
  lightborn: Sun,
  coulrophobia: HeartOff,
  eruption: Radiation,
  "infectious-fright": Volume2,
  "brutal-strength": Pickaxe,
  "a-nurses-calling": Eye,
  stridor: Ear,
  // ---- Teachables (completed roster) ----
  // survivor
  leader: Crown,
  "calm-spirit": Bird,
  saboteur: Scissors,
  "sole-survivor": User,
  "object-of-obsession": Telescope,
  "left-behind": Compass,
  technician: CircuitBoard,
  alert: BellRing,
  "boil-over": Waves,
  "detectives-hunch": Search,
  tenacity: Dumbbell,
  "red-herring": Fish,
  "for-the-people": HandHeart,
  "no-mither": Bandage,
  "were-gonna-live-forever": Ambulance,
  "better-together": Network,
  fixated: Route,
  visionary: Lightbulb,
  "desperate-measures": Stethoscope,
  clairvoyance: Sparkle,
  overcome: Forward,
  "corrective-action": CheckCheck,
  "wake-up": AlarmClock,
  pharmacy: Pill,
  "wide-open-throttle": Rocket,
  "lend-a-hand": Handshake,
  "cross-examination": Fingerprint,
  // killer
  "dragons-grip": Grab,
  "hex-blood-favour": Droplet,
  "hex-haunted-ground": TriangleAlert,
  rancor: Gavel,
  "beast-of-prey": PawPrint,
  "territorial-imperative": Warehouse,
  "hex-huntress-lullaby": Music2,
  "superior-anatomy": ChevronsUp,
  "awakened-awareness": ScanFace,
  terminus: Siren,
  "hex-two-can-play": FlipHorizontal,
  "friends-til-the-end": UserCheck,
  "batteries-included": BatteryCharging,
  "blood-echo": AudioLines,
  nemesis: UserX,
  "zanshin-tactics": Waypoints,
  "hex-nothing-but-misery": Frown,
  "forever-entwined": Link2,
  "none-are-free": LockKeyhole,
  "help-wanted": ClipboardList,
  "phantom-fear": Drama,
  haywire: ZapOff,
  "hex-plaything": Puzzle,
  "scourge-hook-gift-of-pain": Biohazard,
  hoarder: Boxes,
  oppression: Cpu,
  hysteria: EarOff,
  "hex-face-the-darkness": Megaphone,
  hubris: ShieldX,
  "franklins-demise": PackageX,
  "knock-out": MoonStar,
  dissolution: Split,
  "septic-touch": Syringe,
  "hex-the-third-seal": EyeOff,
  "hex-crowd-control": CircleSlash,
  "forced-penance": ShieldOff,
  deathbound: Speech,
  overcharge: BatteryWarning,
  "overwhelming-presence": Hourglass,
  "hex-scared-to-death": OctagonAlert,
  "silent-shadow": CloudFog,
  rampage: Angry,
  // ---- Expanded roster teachables ----
  "hex-wretched-fate": Pentagon,
  "human-greed": Binoculars,
  "dominance": View,
  "gearhead": Locate,
  "hex-retribution": Hexagon,
  "surge": BatteryLow,
  "mindbreaker": BrickWall,
  "cruel-limits": Axe,
  "turn-back-the-clock": TimerOff,
  "secret-project": Snail,
  "hex-hive-mind": FlaskRound,
  "furtive-chase": Glasses,
  "im-all-ears": LocateFixed,
  "thrilling-tremors": Turtle,
  "all-shaking-thunder": Slice,
  "scourge-hook-jagged-compass": Aperture,
  "no-quarter": Bug,
  "hex-overture-of-doom": FlaskConical,
  "ravenous": Navigation,
  "wandering-eye": Webcam,
  "discordance": SatelliteDish,
  "iron-maiden": Radio,
  "mad-grit": Briefcase,
  "weave-attunement": Cctv,
  "languid-touch": Rss,
  "dark-arrogance": Wand,
  "fire-up": Wand2,
  "remember-me": LogOut,
  "blood-warden": Sunset,
  "scourge-hook-floods-of-rage": Focus,
  "call-of-brine": Magnet,
  "merciless-storm": Activity,
  "make-your-choice": Airplay,
  "scourge-hook-hangmans-trick": ScanLine,
  "surveillance": MapPin,
  "save-the-best-for-last": Antenna,
  "play-with-your-food": Box,
  "dying-light": Apple,
  "genetic-limits": Atom,
  "forced-hesitation": Award,
  "machine-learning": Spade,
  "thwack": MapPinned,
  "leverage": Banana,
  "game-afoot": Bean,
  "unnerving-presence": Bed,
  "agitation": Package,
  "unbound": BedDouble,
  "undone": Bell,
  "unforeseen": Shell,
  "predator": Satellite,
  "bloodhound": BellDot,
  "shadowborn": Shapes,
  "alien-instinct": Binary,
  "rapid-brutality": Blocks,
  "ultimate-weapon": Bolt,
  "ace-in-the-hole": Grip,
  "open-handed": BookOpen,
  "up-the-ante": Tag,
  "autodidact": Cross,
  "deliverance": ShieldHalf,
  "diversion": Layers,
  "flip-flop": Component,
  "buckle-up": Bot,
  "mettle-of-man": ShieldQuestion,
  "soul-guard": Medal,
  "blood-pact": Brain,
  "repressed-alliance": Drill,
  "appraisal": BrainCircuit,
  "deception": Cake,
  "power-struggle": Vault,
  "solidarity": Candy,
  "poised": Car,
  "head-on": Sailboat,
  "breakdown": LifeBuoy,
  "aftercare": Castle,
  "distortion": Cat,
  "counterforce": Cherry,
  "resurgence": CircleDashed,
  "blast-mine": Citrus,
  "babysitter": Clapperboard,
  "camaraderie": Cloud,
  "second-wind": CloudRain,
  "lucky-break": Dice5,
  "any-means-necessary": CloudSnow,
  "breakout": Clover,
  "fast-track": Cone,
  "self-preservation": Construction,
  "smash-hit": Contact,
  // ---- Expanded roster: survivors ----
  "wiretap": PlugZap,
  "reactive-healing": Plus,
  "low-profile": Cookie,
  "mirrored-illusion": Cuboid,
  "bardic-inspiration": Settings2,
  "still-sight": Dam,
  "champion-of-light": Database,
  "boon-illumination": Flower,
  "deadline": Diamond,
  "bada-bada-boom": Disc,
  "change-of-plan": Disc3,
  "teamwork-full-circuit": Dog,
  "extrasensory-perception": Drum,
  "we-see-you": Egg,
  "teamwork-soft-spoken": Eclipse,
  "chemical-trap": Factory,
  "light-footed": Fan,
  "lucky-star": Fence,
  "troubleshooter": FerrisWheel,
  "made-for-this": Film,
  "scavenger": Filter,
  "inner-focus": FireExtinguisher,
  "residual-manifest": Flag,
  "overzealous": Flower2,
  "flow-state": Forklift,
  "a-place-for-us": Fuel,
  "five-moves-ahead": Gamepad2,
  "finesse": Gem,
  "hardened": GitBranch,
  "specialist": Globe,
  "bite-the-bullet": GraduationCap,
  "flashbang": Grape,
  "rookie-spirit": Grid2x2,
  "conviction": HandCoins,
  "last-stand": HandMetal,
  "teamwork-throw-down": HardHat,
  "dramaturgy": ChevronsRight,
  "scene-partner": Headphones,
  "plot-twist": Heater,
  "do-no-harm": Highlighter,
  "duty-of-care": Hop,
  "rapid-response": IceCream,
  "better-than-new": Image,
  "reassurance": ShieldPlus,
  "background-player": Inbox,
  "blood-rush": Joystick,
  "teamwork-collective-stealth": Key,
  "apocalyptic-ingenuity": Lamp,
  "come-and-get-me": HandHelping,
  "teamwork-toughen-up": LampDesk,
  "invocation-weaving-spiders": Landmark,
  "strength-in-shadows": Lasso,
  "wicked": Library,
  "invocation-treacherous-crows": LightbulbOff,
  "clean-break": Lollipop,
  "shoulder-the-burden": Luggage,
  "cut-loose": Mailbox,
  "friendly-competition": Martini,
  "teamwork-power-of-two": Maximize,
  "exultation": MemoryStick,
  "moment-of-glory": Mic,
  "eyes-of-belmont": MicOff,
  "road-life": Microscope,
  "one-two-three-four": Milestone,
  "ghost-notes": Mountain,
  "potential-energy": MountainSnow,
  "fogwise": Mouse,
  "parental-guidance": Move,
  "empathic-connection": Notebook,
  "boon-dark-theory": Sprout,
};

const CATEGORY_GLYPH: Record<PerkCategory, LucideIcon> = {
  // survivor
  exhaustion: Wind,
  "aura-reading": Eye,
  "gen-repair": Wrench,
  healing: HeartPulse,
  stealth: EyeOff,
  boon: Sparkles,
  endgame: DoorOpen,
  "anti-tunnel": ShieldCheck,
  totem: Flame,
  utility: Settings,
  // killer
  "gen-slowdown": Gauge,
  hex: Skull,
  "anti-heal": Droplet,
  chase: Footprints,
  tracking: Radar,
  "scourge-hook": Anchor,
};

/** The emblem glyph for a perk: its hand-picked icon, else its primary category. */
export function glyphForPerk(
  slug: string,
  categories: readonly PerkCategory[] | undefined,
  role: Role,
): LucideIcon {
  return PERK_GLYPH[slug] ?? glyphForCategories(categories, role);
}

/** Pick the emblem glyph for a perk from its highest-signal category. */
export function glyphForCategories(
  categories: readonly PerkCategory[] | undefined,
  role: Role,
): LucideIcon {
  if (categories) {
    for (const c of categories) {
      const g = CATEGORY_GLYPH[c];
      if (g) return g;
    }
  }
  // No category match — fall back to a role-flavored default.
  return role === "killer" ? Ghost : ShieldCheck;
}
